### PR TITLE
Add VR2 x VR2PC file and metadata; validate YAML metadata using Yamale

### PR DESCRIPTION
**Pull request by mhpob**
First crack at building out the library.

Receiver: VR2-069kHz
Receiver Firmware: 1.03
Software: VR2PC v 1.00

This PR adds a metadata schema and a GH Action that uses Yamale to validate any `metadata.yaml` files upon pushes to `main` or a pull request. Not sure if Yamale is the best program for the job, but it seems well-supported.

https://github.com/23andMe/Yamale

Still need to find a way to validate the nested citation.cff, likely against their schema: https://github.com/citation-file-format/citation-file-format/blob/main/schema.json

### CODE REVIEW

**Comment by jdpye** [comment]
I was thinking of things like `whip` ( https://github.com/inbo/whip )  when I suggested we use yaml but i like what Yamale seems to be doing to validate the actual metadata entry, not the data it goes along with. (It rhymes with Tamale, right?)

**Comment by mhpob** [comment]
We could set up both! I went with Yamale (rhymes with tamale) since it was updated within the past 3 years, but a quick look makes it seem like whip may be more versatile.

**Comment by mhpob** [comment]
Whip also seems to be something that your corps is already doing. Would you all want to hammer that out?

**Comment by jdpye** [comment]
I'll give it a shot but it might be a while, I'm on the road, you may want to bring this Yamale one home and we'll make a separate branch/PR for whip demo purposes.

**Comment by jdpye** [comment]
I'll take it as-is, it's valuable to start standing up scaffolding and invite other contributions from OTNners like @jackVanish as well as other community leaders like yourself, @benjaminhlina, @hugomflavio and others.

**Comment by benjaminhlina** [comment]
Thanks @mhpob for pioneering this and @jdpye for accepting it...I've been watching how this has come together and like the starting blocks you've put together Mike. Going to implement things on my fork and start adding some data.

**Pull request merged**
